spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers:
      - 192.168.100.30:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:dev.peter.notificationservice.event.OrderPlacedEvent

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://192.168.100.30:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

server:
  port: 0