spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: "mongodb://localhost:27017/product-service"

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://192.168.100.30:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

server:
  port: 0