spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/inventory-service"
    username: "root"
    password:
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://192.168.100.30:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

server:
  port: 0

